name: clone as subtree

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  clone-submodules:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name ${{ github.actor }}
          git pull -s subtree --prefix limiter https://github.com/liranpi2/limiter.git master && git merge -s ours --no-commit --allow-unrelated-histories limiter/master && git commit -m "merge subtree" && git push || echo "No changes to commit"
